[build]
    command="gatsby build"
    publish="public/"
    functions="functions/"

[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    # Get submissions for specific forms
    # e.g. "form-name"
    # e.g. ["form-name-1", "form-name-2"]
    # e.g. "ALL"
    # default: "ALL"
    formNames = "approved-comments"

    dataDirectory = "_data"